server:
  port: 8088
  servlet:
    context-path: /

spring:
  application:
    name: conference-data
  
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3308/conference_db?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: Hnhx@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    out-of-order: false
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
      config:
        server-addr: localhost:8848
        namespace: dev
        file-extension: yml

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    root: info
    com.conference: debug
